# Generated by Django 4.2.4 on 2023-08-21 09:46

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Default text')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/directors'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=256)),
                ('text', models.TextField(default='Default text')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/directors'), upload_to='')),
                ('job_title', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=256)),
                ('days', models.CharField(choices=[('Du', 'DUSHANBA'), ('SE', 'SESHANBA'), ('CHO', 'CHORSHANBA'), ('JU', 'JUMA'), ('SHA', 'SHANBA'), ('YA', 'YAKSHANBA')], max_length=3)),
                ('tel_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.TextField(default='Default text')),
                ('text', models.TextField(default='Default text')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/directors'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField(default='Default text')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.system')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
                ('text', models.TextField(default='Default text')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='subsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subsystem'),
        ),
    ]
